# Generated by Django 5.2.4 on 2025-08-22 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0004_alter_userprofile_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('progress', 'Progress'), ('pattern', 'Pattern'), ('recommendation', 'Recommendation')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='key_insights', to='userprofile.userprofile',to_field='user_id')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_completed', models.PositiveIntegerField(default=0)),
                ('active_days', models.PositiveIntegerField(default=0)),
                ('hours_studied', models.FloatField(default=0)),
                ('motivation_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('completion_percent', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='skills_progress', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DailyEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('hours', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='daily_engagement', to='userprofile.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='MotivationTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='motivation_trends', to='userprofile.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'week_number')},
            },
        ),
    ]
