# Generated by Django 5.2.4 on 2025-08-22 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
        ('userprofile', '0004_alter_userprofile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyinsight',
            name='user_profile',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='key_insights', to='userprofile.userprofile'),
        ),
    ]
