# Generated by Django 5.2 on 2025-08-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_url',
            field=models.URLField(default=''),
        ),
    ]
