# Generated by Django 5.2.4 on 2025-09-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_courses_created_at_alter_courses_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='done',
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in-progress', 'In-progress'), ('not-started', 'Not-started')], default='not-started'),
        ),
    ]
