# Generated by Django 5.2 on 2025-08-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_courses_course_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecontent',
            old_name='roadmap_id',
            new_name='roadmap',
        ),
    ]
