# Generated by Django 5.2.4 on 2025-09-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_coursecontent_done_coursecontent_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='courses',
            name='tutor_academy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
