# Generated by Django 5.2.4 on 2025-09-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_courses_duration_courses_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(blank=True, null=True),
        ),
    ]
