# Generated by Django 5.2 on 2025-08-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_tag_courses_difficulty_courses_rating_courses_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
