# Generated by Django 5.2.4 on 2025-09-10 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_courses_duration'),
        ('userprofile', '0004_alter_userprofile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='duration',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='courses',
            name='overview',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='UserCourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.coursecontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile')),
            ],
            options={
                'unique_together': {('user', 'content')},
            },
        ),
    ]
