# Generated by Django 5.2 on 2025-08-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_courses_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_type',
            field=models.CharField(choices=[('frontend', 'Frontend Development'), ('backend', 'Backend Development'), ('data_science', 'Data Science'), ('mobile', 'Mobile Development'), ('product_management', 'Product Management'), ('ui_ux', 'UI/UX Design'), ('devops', 'DevOps')], default='', max_length=50, null=True),
        ),
    ]
