# Generated by Django 5.2.4 on 2025-09-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_coursecontent_duration_courseenrollment_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
