# Generated by Django 5.2.4 on 2025-09-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_coursecontent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='overview',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
