# Generated by Django 5.2 on 2025-08-18 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_courses_course_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_type',
        ),
    ]
